#!/bin/sh /etc/rc.common
# SPDX-License-Identifier: GPL-3.0-only
# Updated for nftables support by ChatGPT

START=90
STOP=10

EXTRA_COMMANDS="check_status"
EXTRA_HELP="	check_status Check running status of utils"

inital_conf() {
	config_load "turboacc"
	config_get "hw_wed" "config" "hw_wed" "0"
	config_get "hw_flow" "config" "hw_flow" "0"
	config_get "sw_flow" "config" "sw_flow" "0"
	config_get "sfe_flow" "config" "sfe_flow" "0"
	config_get "bbr_cca" "config" "bbr_cca" "0"
	config_get "fullcone_nat" "config" "fullcone_nat" "0"

	[ ! -e "/lib/modules/$(uname -r)/kmod-nft-offload.ko" ] && { sw_flow="0"; hw_flow="0"; }
	[ ! -e "/lib/modules/$(uname -r)/tcp_bbr.ko" ] && bbr_cca="0"
}

load_sfe() {
	local kernel_version=$(uname -r)
	[ -e "/lib/modules/$kernel_version/shortcut-fe-cm.ko" ] && modprobe shortcut-fe-cm
	[ -e "/lib/modules/$kernel_version/fast-classifier.ko" ] && modprobe fast-classifier
}

unload_sfe() {
	[ -d /sys/module/shortcut_fe_cm ] && rmmod shortcut_fe_cm
	[ -d /sys/module/fast_classifier ] && rmmod fast_classifier
}

load_wed() {
	local kernel_version=$(uname -r)
	grep -Eq 'mediatek' /etc/openwrt_release && \
		! grep -Eq 'mt7915e' /etc/modules.conf && \
		[ -e "/lib/modules/$kernel_version/mt7915e.ko" ] && {
			sed -i '$aoptions mt7915e wed_enable=Y' /etc/modules.conf
			rmmod mt7915e && sleep 1 && modprobe mt7915e && wifi up
		}
}

unload_wed() {
	local kernel_version=$(uname -r)
	grep -Eq 'mediatek' /etc/openwrt_release && \
		grep -Eq 'mt7915e' /etc/modules.conf && \
		[ -e "/lib/modules/$kernel_version/mt7915e.ko" ] && {
			sed -i '/mt7915e/d' /etc/modules.conf
			rmmod mt7915e && sleep 1 && modprobe mt7915e && wifi up
		}
}

start() {
	inital_conf

	# nftables offloading is handled by fw4 config
	uci set firewall.@defaults[0].flow_offloading="${sw_flow}"
	uci set firewall.@defaults[0].flow_offloading_hw="${hw_flow}"
	uci set firewall.@defaults[0].fullcone="${fullcone_nat}"
	uci commit firewall

	# Load SFE fallback if nft-offload isn't used
	[ "${sw_flow}" -ne "1" ] && [ "${sfe_flow}" -eq "1" ] && {
		load_sfe
	}

	# Hardware WED
	[ "${hw_flow}" -eq "1" ] && [ "${hw_wed}" -eq "1" ] && {
		load_wed
	}

	# BBR Congestion Control
	if [ "${bbr_cca}" -eq "1" ]; then
		sysctl -w net.ipv4.tcp_congestion_control="bbr"
	else
		sysctl -w net.ipv4.tcp_congestion_control="cubic"
	fi

	/etc/init.d/firewall reload
}

stop() {
	inital_conf

	# Preserve UCI state (not necessary, but kept for consistency)
	uci set firewall.@defaults[0].flow_offloading="${sw_flow}"
	uci set firewall.@defaults[0].flow_offloading_hw="${hw_flow}"
	uci set firewall.@defaults[0].fullcone="${fullcone_nat}"
	uci commit firewall

	[ "${hw_wed}" -eq "0" ] && {
		unload_wed
	}

	unload_sfe

	/etc/init.d/firewall reload
}

restart() {
	stop
	start
}

check_status() {
	case "$1" in
	"fastpath")
		if nft list chain inet fw4 forward | grep -q offload; then
			echo -n "nftables Flow Offloading"
			exit 0
		elif [ -d /sys/module/fast_classifier ]; then
			echo -n "Shortcut-FE"
			exit 0
		elif [ -d /sys/module/shortcut_fe_cm ]; then
			echo -n "Shortcut-FE ECM"
			exit 0
		else
			exit 1
		fi
		;;
	"fullconenat")
		if nft list ruleset | grep -iq fullcone; then
			exit 0
		else
			exit 1
		fi
		;;
	"bbr")
		[ "$(cat /proc/sys/net/ipv4/tcp_congestion_control)" = "bbr" ] && exit 0 || exit 1
		;;
	*)
		exit 2
		;;
	esac
}
