#!/bin/sh

FEEDS_FILE="/etc/opkg/customfeeds.conf"
FEEDS_URL="https://dotywrt.github.io/dotywrt/v3.1/packages"

add_feed() {
    FEED_LINE="$1"
    grep -qxF "$FEED_LINE" "$FEEDS_FILE" || echo "$FEED_LINE" >> "$FEEDS_FILE"
}


add_feed "src/gz dotywrt $FEEDS_URL"

wget -q -O /tmp/passwall.pub "$FEEDS_URL/passwall.pub"
[ -f /tmp/passwall.pub ] && opkg-key add /tmp/passwall.pub && rm -f /tmp/passwall.pub

rm -f "$0"
exit 0
